spring.application.name=Traffic Light Controller
server.port=8082

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration


spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none
traffic.skip.max=8

#Timer for each signal

traffic.phase.value.NS_LEFT_GREEN=20
traffic.phase.value.NS_LEFT_YELLOW=4
traffic.phase.value.NS_STRAIGHT_PERMISSIVE=30
traffic.phase.value.NS_STRAIGHT_YELLOW=4

traffic.phase.value.EW_LEFT_GREEN=20
traffic.phase.value.EW_LEFT_YELLOW=4
traffic.phase.value.EW_STRAIGHT_PERMISSIVE=30
traffic.phase.value.EW_STRAIGHT_YELLOW=4
